<a href="https://colab.research.google.com/github/dakshesh-1293/AI-ML-Training/blob/main/Classwork/Scikit-Learn/Encoding/Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is Encoding?

>Machine Learning algorithms understand numbers, not text.

>- Encoding is one of the most important preprocessing steps in Machine Learning interviews and real-world projects


### Types of Encoding

In real projects you'll mostly use

1. Label Encoding
2. One Hot Encoding
3. Ordinal Encoding
4. Frequency Encoding
5. Target Encoding
6. Binary Encoding
7. Count Encoding

## --Algorithms like Linear Regression, Logistic Regression, SVM, KNN cannot directly use these values.

### Which Encoding Should You Use?

| Scenario                                              | Recommended Encoding     | Why?                                                              |
| ----------------------------------------------------- | ------------------------ | ----------------------------------------------------------------- |
| Gender (Male/Female)                                  | Label Encoding           | Two categories, simple binary feature                             |
| Yes/No, True/False                                    | Label Encoding           | Binary categorical data                                           |
| City, Color, Department (few unique values)           | One Hot Encoding         | No natural order, avoids false ranking                            |
| Education, Size, Rating                               | Ordinal Encoding         | Categories have a meaningful order                                |
| Country, Product ID, Company (many unique values)     | Frequency/Count Encoding | Reduces the number of features                                    |
| High-cardinality categories with enough training data | Target Encoding          | Can capture relationships with the target, but must avoid leakage |
| Extremely high-cardinality data                       | Binary Encoding          | More memory-efficient than one-hot encoding                       |

## 1. Label Encoding

Used when a column has only two categories.

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.DataFrame({
    "Gender":["Male","Female","Male","Female"]
})

df

   Gender
0    Male
1  Female
2    Male
3  Female

In [ ]:
encoder = LabelEncoder()

df["Gender"] = encoder.fit_transform(df["Gender"])

print(df)

   Gender
0       1
1       0
2       1
3       0

### When to use Label Encoding?
>Binary column

- Yes/No
- Male/Female
- True/False


**Advantages**

 Very simple

 Fast

 Uses only one column

 Memory efficient

**Disadvantages**

 Introduces false ordering

**Where NOT to use?**

 City

 Country

 Color

 Department

because there is no order.

## 2. One Hot Encoding
- Most commonly used.
> Instead of numbers

> Create new columns.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "City":["Pune","Delhi","Mumbai","Pune"]
})

df

     City
0    Pune
1   Delhi
2  Mumbai
3    Pune

In [ ]:
encoded = pd.get_dummies(df,
                         columns=["City"],
                         dtype=int)

print(encoded)

   City_Delhi  City_Mumbai  City_Pune
0           0            0          1
1           1            0          0
2           0            1          0
3           0            0          1

In [ ]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)

result = encoder.fit_transform(df[["City"]])

print(result)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

#### When to use?

Small number of categories

Gender

Department

Payment Mode

Color


**Advantages**

 No false ordering

 Most widely used

 Works well with most ML algorithms

 Easy to understand


**Disadvantages**
Creates many columns(COD)

## 3. Ordinal Encoding
Used when categories have order.
>Assigns numbers while preserving order.

Education

- High School
- Graduate
- Post Graduate
- PhD

PhD > PG > Graduate

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd

df = pd.DataFrame({
    "Education":[
        "Graduate",
        "PhD",
        "High School",
        "Post Graduate"
    ]
})

df

       Education
0       Graduate
1            PhD
2    High School
3  Post Graduate

In [ ]:
encoder = OrdinalEncoder(categories=[[
    "High School",
    "Graduate",
    "Post Graduate",
    "PhD"
]])

df["Education"] = encoder.fit_transform(df[["Education"]])

print(df)

   Education
0        1.0
1        3.0
2        0.0
3        2.0

#### **Customer Satisfaction**
- Poor
- Average
- Good
- Excellent


#### When to use?

Whenever order exists.


- Education
- Size
- Low Medium High
- Rating
- Bronze Silver Gold Platinum

**Advantages**

 Keeps natural order

 Only one column

 Memory efficient

**Disadvantages**

| Wrong if no order exists

**Where NOT to use?**

City

Country

Department

Color

## 4. Frequency Encoding

Replace category with frequency.

City,
Pune,
Delhi,
Pune,
Mumbai,
Pune

**Frequency**
- Pune = 3
- Delhi =1
- Mumbai =1

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "City":[
        "Pune",
        "Delhi",
        "Pune",
        "Mumbai",
        "Pune"
    ]
})

df

     City
0    Pune
1   Delhi
2    Pune
3  Mumbai
4    Pune

In [ ]:
frequency = df["City"].value_counts()

df["City"] = df["City"].map(frequency)

print(df)

   City
0     3
1     1
2     3
3     1
4     3

#### Used in

High-cardinality features

Country

State

City

Company Name

**Advantages**

 Only one column

 Good for high-cardinality data

 Saves memory

**Disadvantages**

Delhi = 10

Mumbai =10

Info lost

### 5. Count Encoding

### 6. Target Encoding

Very popular in Kaggle.

We have **City**

Target > House Price

- **Average price**

Pune = 60 lakh

Delhi = 80 lakh

Mumbai = 1.2 Cr


Replace city with average target.

Pune

↓

60

| City  | Price |
| ----- | ----- |
| Pune  | 60    |
| Delhi | 80    |
| Pune  | 55    |
| Delhi | 90    |


Pune =57.5

Delhi =85

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "City":["Pune","Delhi","Pune","Delhi"],
    "Price":[60,80,55,90]
})

df

    City  Price
0   Pune     60
1  Delhi     80
2   Pune     55
3  Delhi     90

In [ ]:
mean = df.groupby("City")["Price"].mean()
mean

City
Delhi    85.0
Pune     57.5
Name: Price, dtype: float64

In [ ]:
df["City"] = df["City"].map(mean)

print(df)

   City  Price
0  57.5     60
1  85.0     80
2  57.5     55
3  85.0     90

**Problem**

Can cause data leakage if you calculate the target mean using the full dataset before splitting. In practice, compute target encoding using only the training data (often with cross-validation or smoothing).

## What is it?
## Advantages
## Disadvantages
## Where to use?